### ISSUE TITLE
How to use grad cache for higher batch size?

### ISSUE THREAD

**Issue by sandeep-krutrim** [nomic-ai/contrastors#32]
I am trying to make the batch-size as 4096 with seq-len 2048 on 8xH100 80GB GPUs.  My config file is- 

> train_args:
>   num_epochs: 20
>   learning_rate: 1.0e-3
>   adam_beta1: 0.9
>   adam_beta2: 0.98
>   weight_decay: 1.0e-5
>   eps: 1.0e-6
>   max_grad_norm: 0.0
>   schedule_type: "linear"
>   gradient_accumulation_steps: 1 
> 
>   warmup_steps: 0
>   warmup_pct: 0.06
>   cooldown_steps: null
>   checkpoint: null
> 
>   wandb: True
>   wandb_project_name: "abc"
>   wandb_entity: "xyz"
> 
>   log_grads_every: 10
>   log_lr_every: 10
>   save_every: 10
>   eval_every: 10
>   eval_strategy: "steps"
>   eval_steps: 10
>   output_dir: "/disk1/sandeep/ckpts/"
>   # if using deepspeed, this will be ignored
>   pretrained: null
>   pooling: "last"
>   use_fp8: false
>   grad_cache: true
>   chunk_size: 8
> 
> model_args:
>   "model_type": "mlm"
>   seq_len: 2048
>   rotary_emb_fraction: 1.0
>   pad_vocab_to_multiple_of: 64 
>   use_rms_norm: false
>   activation_function: "swiglu"
>   tokenizer_name: "/disk1/sandeep/tokenizer_custom/"
>   model_name: 'nomic-ai/nomic-bert-2048'
>   qkv_proj_bias: false
>   mlp_fc1_bias: false
>   mlp_fc2_bias: false
>   attn_pdrop: 0.0
>   gradient_checkpointing: false
> 
> mlm_data_args:
>   tokenized_dataset: "sandeep/mydata"
>   workers: 8
>   batch_size: 4096
>   seed: 42
>   shuffle: true
>   mlm_prob: 0.15
>   val_mlm_prob: 0.15
>   val_pct: 0.01
> 
> deepspeed: true

   
I am getting the following error on run -  
```
Total training steps: 1212                                                                                                                                                                        
Epoch 0:   0%|                                                                                                                                                           | 0/1212 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                
  File "/disk1/sandeep/contrastors/src/contrastors/train.py", line 74, in <module>                                                                                                                
    main(config, args.dtype)                                                                                                                                                                      
  File "/disk1/sandeep/contrastors/src/contrastors/train.py", line 57, in main                                                                                                                    
    trainer.train()                                                                                                                                                                               
  File "/disk1/sandeep/contrastors/src/contrastors/trainers/base.py", line 383, in train                                                                                                          
    loss = self.training_step(                                                                                                                                                                    
  File "/disk1/sandeep/contrastors/src/contrastors/trainers/base.py", line 322, in training_step                                                                                                  
    loss = self.forward_step(inputs=batch, **model, step=step)                                                                                                                                    
  File "/disk1/sandeep/contrastors/src/contrastors/trainers/mlm.py", line 123, in forward_step                                                                                                    
    output = model(**inputs)                                                                                                

  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/sandeep/contrastors/src/contrastors/models/encoder/modeling_nomic_bert.py", line 453, in forward
    outputs = self.bert(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/sandeep/contrastors/src/contrastors/models/encoder/modeling_nomic_bert.py", line 381, in forward
    sequence_output = self.encoder(hidden_states, attention_mask=attention_mask)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/sandeep/contrastors/src/contrastors/models/encoder/modeling_nomic_bert.py", line 216, in forward
    hidden_states, hidden_states2, residual = layer(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/sandeep/contrastors/src/contrastors/layers/block.py", line 306, in forward
    attn_outputs = self.attn(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/sandeep/contrastors/src/contrastors/layers/attention.py", line 133, in forward
    attn_outputs = flash_attn_varlen_qkvpacked_func(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 887, in flash_attn_varlen_qkvpacked_func
    return FlashAttnVarlenQKVPackedFunc.apply(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 288, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/disk1/sandeep/miniconda3/envs/nomic2/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 85, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
TypeError: varlen_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: Optional[torch.Tensor], arg4: torch.Tensor, arg5: torch.Tensor, arg6: Optional[torch.Tensor], arg7: Optional[torch.Tenso
r], arg8: int, arg9: int, arg10: float, arg11: float, arg12: bool, arg13: bool, arg14: int, arg15: int, arg16: bool, arg17: Optional[torch.Generator]) -> List[torch.Tensor]

Invoked with: <repr raised Error>, <repr raised Error>, <repr raised Error>, None, <repr raised Error>, <repr raised Error>, None, None, 2048, 2048, 0.0, <repr raised Error>, False, False, -1, -
1, False, None
`
```

**Comment by zanussbaum** [comment]
You can't use grad cache with Masked language modeling, it's only used for contrastive training which is probably why you're seeing the error below (which is most likely an OOM).

You can do gradient accumulation however by setting `gradient_accumulation_steps` to something > 1 and your batch size to something smaller. For example if you want to keep a batch size of 4096, you can try something like a batch size of 512 and gradient accumulation steps of 8 but YMMV. I don't remember off the top of my head what I used when we pretrained the model but we did use gradient accumulation

**Comment by sandeep-krutrim** [comment]
Thanks zach for the clarification.

I can train with gradient accumulation of 8 now as suggested by you. I am trying to do MLM on 10B tokens with seq len 2048 and 15 percent masking. However even running for 200k steps, I am not observing any learning when checked qualitatively for mask filling.  Do longer seq len require more tokens and training steps to learn.  

On the contrary, with huggingface trainer and seq len 128 with same amount of tokens, i observed good performance on 250k steps.  Any suggestions would be helpful. Thanks in advance.

**Comment by zanussbaum** [comment]
Hey Sandeep, how are you measuring if it works well? We trained masking set to 30%. I'm not sure if this is a data issue or hyperparameter issue. We primarily measured the quality of our model using GLUE and seemed to reach similar results to other BERT models.

**Comment by sandeep-krutrim** [comment]
Hi Zach,

I am doing a qualitative check using - 
`from transformers import AutoModelForMaskedLM, AutoConfig, AutoTokenizer, pipeline


tokenizer = AutoTokenizer.from_pretrained('custom_tokenizer') 
if tokenizer.cls_token is None:
    tokenizer.add_special_tokens({"cls_token": "[CLS]","sep_token":"[SEP]"})



model_path = model_base + 'epoch_19/model/'


config = AutoConfig.from_pretrained(model_path, trust_remote_code=True) # the config needs to be passed in
model = AutoModelForMaskedLM.from_pretrained(model_path,config=config,trust_remote_code=True)
model.eval()

classifier = pipeline('fill-mask', model=model, tokenizer=tokenizer,device="cpu")`

I am checking for mask filling. one such example is - 
`sent = "मैं कल बाजार <mask> था"
classifier(sent)`

The output for this is - 

> Score: 0.7190290689468384
> Token: 468
> Token String: -
> Sequence: मैं कल बाजार  -  था
> ------------------------
> Score: 0.11437328904867172
> Token: 99223
> Token String: 1
> Sequence: मैं कल बाजार 1  था
> ------------------------
> Score: 0.0300486758351326
> Token: 99173
> Token String: 
> Sequence: मैं कल बाजार    था
> ------------------------
> Score: 0.017167197540402412
> Token: 99375
> Token String: 4
> Sequence: मैं कल बाजार 4  था
> ------------------------
> Score: 0.015724895521998405
> Token: 99344
> Token String: 5
> Sequence: मैं कल बाजार 5  था

If MLM pretraining is happening, then the checkpoints should progressively improve on mask filling , isnt it ?

**Comment by zanussbaum** [comment]
Yes it should get better, although this is one example so it's hard to tell if the model is learning or not (and I only speak English so I'm not sure I can offer any great insights on the above example). This may be an issue with the tokenizer not representing the words very well as BERT is known to have a poor tokenizer for non-romance languages.
