### ISSUE TITLE
Unable to run MLM pretraining on 8xH100 GPU server.

### ISSUE THREAD

**Issue by sandeep-krutrim** [nomic-ai/contrastors#64]
I follow the steps to install the libraries and then run pretraining for MLM

I get the following error - 
`Traceback (most recent call last):
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/train.py", line 10, in <module>
    from trainers import TRAINER_REGISTRY
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/trainers/__init__.py", line 2, in <module>
    from .glue import *
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/trainers/glue.py", line 9, in <module>
    from models import NomicBertConfig, NomicBertForSequenceClassification
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/models/__init__.py", line 1, in <module>
    from .biencoder import *
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/models/biencoder/__init__.py", line 2, in <module>
    from .modeling_biencoder import *
  File "/home/sandeep.pandey/experiments/contrastors/src/contrastors/models/biencoder/modeling_biencoder.py", line 8, in <module>
    from flash_attn.bert_padding import pad_input, unpad_input
  File "/home/sandeep.pandey/experiments/nomic2/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/sandeep.pandey/experiments/nomic2/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/sandeep.pandey/experiments/nomic2/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv
`

**Comment by zanussbaum** [comment]
This seems like a library error. You may need to reinstall everything and comment out the torch and flash-attn lines from here: https://github.com/nomic-ai/contrastors/blob/main/requirements.txt#L36
